# Generated by Django 5.1.7 on 2025-05-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessorio_cor_modelo_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(related_name='veiculos', to='core.acessorio'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.modelo'),
        ),
    ]
